<?php

/**
 * @file
 * Csas tooltip
 */

/**
 * Implements hook_library().
 */
function csas_tlt_library() {
  $path = drupal_get_path('module', 'csas_tlt');
  $libraries['csas-tlt'] = array(
    'title' => 'Csas tooltip',
    'version' => '1.0',
    'js' => array(
      $path . '/js/csas_tlt.js' => array(),
    ),
    'css' => array(
      $path . '/css/csas_tlt.css' => array(),
    ),
  );
  return $libraries;
}